# A workflow to automatically convert markdown to pdf.

name: md2pdf


on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex
        with:
          args: -f markdown-raw_tex --pdf-engine=xelatex slide.md -o output/slide.pdf
      - uses: actions/upload-artifact@master
        with:
          name: slide
          path: output
